language: bash
services: docker

env:
  - VERSION=0.29
  - VERSION=1.0

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - cd "$VERSION"
  - image="pgolm/sensu:${VERSION}"

script:
  - travis_retry docker build -t "$image" .
  - ~/official-images/test/run.sh "$image"

after_script:
  - docker images
