FROM pgolm/sensu:latest

ARG PLUGINS
ENV SENSU_PLUGINS=${PLUGINS}

RUN \
    apt-get update &&\
    apt-get install -y libxml2 libxml2-dev libxslt1-dev zlib1g-dev build-essential &&\
    sensu-install -P $SENSU_PLUGINS &&\
    apt-get remove -y libxml2 libxml2-dev libxslt1-dev zlib1g-dev build-essential
